spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
#    database-platform: oorg.hibernate.dialect.MySQLDialect
